### ISSUE TITLE
Recrutement des autres personnages

### ISSUE THREAD

**Issue by Trishng** [task-tim/temps#43]
- [ ] le professeur
- [ ] camarade de classe #1
- [ ] camarade de classe #2 
- [ ] camarade de classe #3
- [ ] camarade de classe #4
